### ISSUE TITLE
데이터베이스 설계

### ISSUE THREAD

**Issue by KangWooJin** [ChallengeProject/QuizTogether#1]

**Comment by KangWooJin** [comment]
# broadcast
<pre>
CREATE TABLE `broadcast` (
  `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `title` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  `description` varchar(300) CHARACTER SET utf8 DEFAULT NULL,
  `broadcast_status` tinyint(4) DEFAULT NULL,
  `prize` bigint(20) DEFAULT NULL,
  `gift_description` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `gift_type` tinyint(4) DEFAULT NULL,
  `winner_message` varchar(200) CHARACTER SET utf8 DEFAULT NULL,
  `code` varchar(100) DEFAULT NULL,
  `is_public` tinyint(4) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `updated_time` timestamp(3) NULL DEFAULT NULL,
  `scheduled_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
</pre>

**Comment by KangWooJin** [comment]
# Chat

<pre>
CREATE TABLE `chat` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `broadcast_id` bigint(20) DEFAULT NULL,
  `chat_url` varchar(300) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
</pre>

**Comment by KangWooJin** [comment]
# push
<pre>
CREATE TABLE `push` (
  `seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `message` varchar(300) DEFAULT NULL,
  `broadcast_id` bigint(20) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `push_type` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
</pre>

**Comment by KangWooJin** [comment]
# quiz_question
<pre>
CREATE TABLE `quiz_question` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `broadcast_id` bigint(20) DEFAULT NULL,
  `step` int(11) DEFAULT NULL,
  `qeustion` varchar(1000) CHARACTER SET utf8 DEFAULT NULL,
  `answer_no` int(11) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `updated_time` timestamp(3) NULL DEFAULT NULL,
  `category` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
</pre>

**Comment by KangWooJin** [comment]
# stream
<pre>
CREATE TABLE `stream` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `broadcast_id` bigint(20) DEFAULT NULL,
  `stream_status` tinyint(4) DEFAULT NULL,
  `streaming_url` varchar(300) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `updated_time` timestamp(3) NULL DEFAULT NULL,
  `started_time` timestamp(3) NULL DEFAULT NULL,
  `completed_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
</pre>

**Comment by KangWooJin** [comment]
# user
<pre>
CREATE TABLE `user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(40) CHARACTER SET utf8 DEFAULT NULL,
  `user_status` tinyint(4) DEFAULT NULL,
  `profile_path` varchar(300) DEFAULT NULL,
  `money` bigint(20) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `update_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
</pre>

**Comment by KangWooJin** [comment]
# user_answer_history
<pre>
CREATE TABLE `user_answer_history` (
  `seq` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(11) DEFAULT NULL,
  `boradcast_id` bigint(11) DEFAULT NULL,
  `step` int(11) DEFAULT NULL,
  `answer_no` int(11) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
</pre>

**Comment by KangWooJin** [comment]
# user_device
<pre>
CREATE TABLE `user_device` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `uuid` varchar(300) CHARACTER SET utf8 DEFAULT NULL,
  `push_token` varchar(300) CHARACTER SET utf8 DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `updated_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
</pre>

**Comment by KangWooJin** [comment]
# user_prize_history
<pre>
CREATE TABLE `user_prize_history` (
  `seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `amount` bigint(20) DEFAULT NULL,
  `broadcast_id` bigint(11) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
</pre>

**Comment by KangWooJin** [comment]
# redis
## play_user
```
key : playUser:broadcastId:step
value : userId
```
##### discription
<pre>
첫 번째 문제를 제외하고 현재 step-1에 userId가 존재하지 않으면 탈락한 유저
</pre>

## play_user_answer
```
key : playUserAnswer:broadcastId:userId:step
value : answerNo

```
##### discription
<pre>
현재 step의 user가 제출한 정답을 저장
</pre>

## current_viwers
```
key : viewers:braodcastId:userId
value : 
```
##### discription
<pre>
현재 시청하고 있는 user의 수
자료구조 Set을 이용해서 userId의 갯수를 통해 시청자를 구한다. 
</pre>

## current_broadcast_step
```
key : broadcastStep:braodcastId
value : step
```
##### discription
<pre>
현재 방송의 step의 번호를 저장해 둔다.
</pre>

**Comment by tyburn117** [comment]
### BroadCast
```sql
CREATE TABLE `broadcast` (
  `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT, -- 아이디
  `user_id` bigint(20) DEFAULT NULL, -- 유저 아이디
  `title` varchar(50) CHARACTER SET utf8 DEFAULT NULL, --타이틀 
  `description` varchar(300) CHARACTER SET utf8 DEFAULT NULL, --설명
  `broadcast_status` tinyint(4) DEFAULT NULL, --broadcast_status 이건 무엇이냐? 
  `prize` bigint(20) DEFAULT NULL, --상금은 무조건 돈으로만 ? 
  `gift_description` varchar(100) CHARACTER SET utf8 DEFAULT NULL, --상품 설명
  `gift_type` tinyint(4) DEFAULT NULL,  -- gift_type? 혹시 결정된거 있는지?
  `winner_message` varchar(200) CHARACTER SET utf8 DEFAULT NULL, -- 승리코멘트
  `code` varchar(100) DEFAULT NULL,   --코드? 이건 무슨 코드인지?
  `is_public` tinyint(4) DEFAULT NULL,   --공개 여부
  `created_time` timestamp(3) NULL DEFAULT NULL, --생성시간
  `updated_time` timestamp(3) NULL DEFAULT NULL, --수정시간
  `scheduled_time` timestamp(3) NULL DEFAULT NULL, --게임시작시간
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by tyburn117** [comment]
### Chat
```sql
CREATE TABLE `chat` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `broadcast_id` bigint(20) DEFAULT NULL,
  `chat_url` varchar(300) DEFAULT NULL,    -- 채팅방 URL
  `created_time` timestamp(3) NULL DEFAULT NULL, -- 채팅방 생성시간 <- 이건 왜 필요한지? 
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1; -- 참고로 charset latin1으로 하면 한글 깨지지 않음? 
```

**Comment by tyburn117** [comment]
### Push

Push가 무엇인지 잘 모르겠지만, Chat방에 Message를 보내는 걸로 이해함

```sql
CREATE TABLE `push` (
  `seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `message` varchar(300) DEFAULT NULL,    -- 보낼 메시지
  `broadcast_id` bigint(20) DEFAULT NULL,  -- 쳇방 아이디가 있는데?  아니면 Chat방에 메시지를 보내는 것이 아닌가
  `created_time` timestamp(3) NULL DEFAULT NULL, -- 보낼 메시지 생성시간? 흠..
  `push_type` tinyint(4) DEFAULT NULL, -- push의 종류가 무엇이 있는지 언급 필요
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by tyburn117** [comment]
### Quiz Question
테이블 수정이 필요함
qustion 컬럼과 answer_no 컬럼이 중복됨 
Quiz라는 테이블을 만들고 Question테이블 내 문제를  여러개 만들던가 할 필요가 있어 보임
Quiz  ---1----M--- Question

```sql
CREATE TABLE `quiz_question` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `broadcast_id` bigint(20) DEFAULT NULL,
  `step` int(11) DEFAULT NULL,    -- 단계 
  `question` varchar(1000) CHARACTER SET utf8 DEFAULT NULL,
  `answer_no` int(11) DEFAULT NULL, -- 정답 번호 
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `updated_time` timestamp(3) NULL DEFAULT NULL,
  `category` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by tyburn117** [comment]
### Stream

영상관련 테이블로 보임
```sql
CREATE TABLE `stream` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `broadcast_id` bigint(20) DEFAULT NULL,
  `stream_status` tinyint(4) DEFAULT NULL,
  `streaming_url` varchar(300) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `updated_time` timestamp(3) NULL DEFAULT NULL,
  `started_time` timestamp(3) NULL DEFAULT NULL,
  `completed_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

개인적인 생각인데, 시간을 등록한 이유가 나중에 히스토리를 만들려고 하는 것 같은데
사람 수가 많으면 디비 과부하가 심해질 가능성이 있음(사실 잘될 가능성이 얼마나 될까..)
그래서 그냥 로그만 남기고 나중에 따로 cron으로 관리하는 것이 부하를 줄이는 방법

**Comment by tyburn117** [comment]
### User

```sql
CREATE TABLE `user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(40) CHARACTER SET utf8 DEFAULT NULL,
  `user_status` tinyint(4) DEFAULT NULL,
  `profile_path` varchar(300) DEFAULT NULL,
  `prize` bigint(20) DEFAULT NULL,      -- 이건 왜 있는지? 
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `update_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by tyburn117** [comment]
### user_answer_history
```sql
CREATE TABLE `user_answer_history` (
  `seq` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(11) DEFAULT NULL,
  `boradcast_id` bigint(11) DEFAULT NULL, 
  `step` int(11) DEFAULT NULL, -- 각 스텝마다 매번 저장할 것인가? 고민
  `answer_no` int(11) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by tyburn117** [comment]
### user_device
이 테이블은 왜 있는거야? 
```sql
CREATE TABLE `user_device` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `uuid` varchar(300) CHARACTER SET utf8 DEFAULT NULL,
  `push_token` varchar(300) CHARACTER SET utf8 DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  `updated_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by tyburn117** [comment]
### user_prize_history
```sql
CREATE TABLE `user_prize_history` (
  `seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `amount` bigint(20) DEFAULT NULL, -- 상품이 무조건 상금이 아닐 수 있잖아? 그리고 DB로 관리해서 머하징.. 
  `broadcast_id` bigint(11) DEFAULT NULL,
  `created_time` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by tyburn117** [comment]
## 총평
1.일단, IOPS가 높은 테이블은 모두 Redis로 옮기고 한 게임이 끝나면 정리 식으로 저장을 한다는 식으로 해야할 듯
2. 게임이 많아지면 DB 과부하 생각해야함.

**Comment by KangWooJin** [comment]
1. 1단계가 아닌 것들은 추후 고민(push, stream, history)
2. prize_history에서는 상금, 상품에 대해서 추가

**Comment by KangWooJin** [comment]
user에 prize -> money로 변경

**Comment by KangWooJin** [comment]
user테이블에 deleted_time 추가

**Comment by KangWooJin** [comment]
Broadcast table에 question_count 추가
