### ISSUE TITLE
문제 진행시 Broadcast Status 변경

### ISSUE THREAD

**Issue by KangWooJin** [ChallengeProject/QuizTogether#19]
- [x] user가 join시에 wating, openQuestion, openAnswer, openWinners만 가능
- [x] 문제 제출, 정답 공개, 우승자 공개시에 broadcast의 status가 변경 되어야 한다.
- [ ] 다음 단계로 진행 시에 해당 broadcast의 status를 확인 하는 logic 필요
- [ ] 정답 공개시에 해당 broadcast의 정답 마감시간 이후인지 확인하는 logic 필요
-> 추후

**Comment by KangWooJin** [comment]
broadcastStatus 체크 부분은 전 단계 가능한 status와 다음 단계 가능한 status가 필요해 보임
<pre>
STATUS(before, next)
CREATED({}, WATING)
WATING(CREATED, {OPEN_QUESTION,OPEN_ANSWER,OPEN_WINNERS})
OPEN_QUESTION ({WATING, OPEN_ANSWER}, {WATING, OPEN_ANSWER})
OPEN_ANSWER ({WATING, OPEN_QUESTION}, {WATING, OPEN_QUESTION})
OPEN_WINNERS ({WATING, OPEN_ANSWER}, {WATING, COMPLETED})
COMPLETED ({WATING, OPEN_WINNERS}, {})
</pre>

@seose WATING 상태 없이 바로 다음 상태로 가는방법이랑 중간에 WATING이 무조건 있는 방식 중에 어떤 것이 좋은지 검토 바랍니다.

**Comment by seose** [comment]
진행자 클라이언트에서 퀴즈화면 -> wating 혹은 답화면 -> wating 로 넘어갈때 rest요청을 드리겠습니다. 
wating -> 위너 -> 종료
해당 규약을 정할 필요가 있어보입니다

**Comment by seose** [comment]
추후에 퀴즈풀이자가 나갔다 들어왔을때 남은시간 방안으로 디바이스 내의 로컬타임을 이용해도될것같습니다. 검토해보겠습니다
