### ISSUE TITLE
main list 시작 전 text 서버처리

### ISSUE THREAD

**Issue by seose** [ChallengeProject/QuizTogether#27]
![image](https://user-images.githubusercontent.com/32695143/43367225-be289f36-9384-11e8-9c21-d4ea039e5d96.png)

main list 에서 보통 시간이 표기되지만, 
시작 5분전? 부터 시간text가 바뀐다
이부분을 서버에서 처리한다

(클라에서의 시간이 각각 다를 수 도 있기때문에)

**Comment by KangWooJin** [comment]
fix f8c63cb9d26182bd24b93b76a525781ddf2208a3
