### ISSUE TITLE
openAnswer에 QuestionStatistics DataType 결정

### ISSUE THREAD

**Issue by KangWooJin** [ChallengeProject/QuizTogether#34]
- [x] Map
- [ ] List

Map으로 해야 하는 이유 : list의 경우 3번만 체크되어 있는 경우 3번의 index가 0번으로 들어가서 알 수가 없음.. 이 부분은 서버에서 Map을 다시 List로 바꾸는 작업을 해야 하는데 현재 보기의 갯수가 3개라서 가능하지만 보기의 최대 갯수를 알 수 없으면 구현하기 힘들 것 같습니다.

**Comment by seose** [comment]
sure!
