### ISSUE TITLE
참여자가 같은 문제에 답을 2번 내는 버그

### ISSUE THREAD

**Issue by KangWooJin** [ChallengeProject/QuizTogether#38]
- [x] 참여자가 답을 2번 내서 통계를 증가 시키는 버그 해결하기

**Comment by seose** [comment]
현재는 답을 두번 못내게 되있습니다.
테스트편의상 추가 방을 개설하지않고 한방을 여러게 쓰는 상황과
틀리고 재접속할때의 처리(https://github.com/ChallengeProject/QuizTogether/issues/67) 가 안되있어 클라이언트쪽의 이슈라고 생각합니다
