### ISSUE TITLE
getBroadcastList api 프로퍼티 추가 필요

### ISSUE THREAD

**Issue by seose** [ChallengeProject/QuizTogether#40]
getBroadcastList api에 

description 프로퍼티가 추가로 필요해 보입니다

![image](https://user-images.githubusercontent.com/32695143/43908461-0010055e-9c33-11e8-8f7a-5c1c7fab1a06.png)

검토 바랍니다

**Comment by seose** [comment]
db 테이블에는 해당 컬럼이 있더라구요

**Comment by KangWooJin** [comment]
추가 했습니다~
